# for travis-ci
# see also. https://travis-ci.org
git:
  submodules: false

language: php
sudo: false
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
php:
  - 5.6

#services:
#  - mysql

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - env: DB=mysql
#  exclude:
#    - php: 5.6
#      env: DB=pgsql USER=postgres DBNAME=myapp_test DBPASS=password DBUSER=postgres
#  allow_failures:
#    - php: hhvm
#    - php: 7.0
#    - php: 5.3.3
#    - PHP: 5.3
#      env: DB=sqlite
#    - PHP: 5.4
#      env: DB=sqlite
#    - PHP: 5.5
#      env: DB=sqlite
#    - PHP: 5.6
#      env: DB=mysql USER=root DBNAME=cube3_dev DBPASS='password' DBUSER=cube3_dev_user
env:
  - DB=mysql

#  - DB=pgsql USER=postgres DBNAME=myapp_test DBPASS=password DBUSER=postgres
#  - DB=sqlite

install:
  - gem install mime-types -v 2.99.1
#  - gem install mailcatcher

before_script:
  - composer self-update || true
  - composer install --dev --no-interaction -o
  - sh -c "if [ '$DB' = 'mysql' ]; then sh ./eccube_install.sh mysql none; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then sh ./eccube_install.sh pgsql none; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then sh ./eccube_install.sh sqlite3 none; fi"
#  - mailcatcher

script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then phpunit --coverage-clover=coverage.clover ; fi
  - if [[ $TRAVIS_PHP_VERSION =~ ^[57] ]]; then phpunit ; fi

after_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; fi

branches:
  only:
    - /^admin_.*$/
# after_failure:
#   - 'cat app/log/site_`date +"%Y-%m-%d"`.log'
